services:
  nav-center:
    container_name: nav-center
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      ADMIN_PASSWORD: "123456"
    volumes:
      - ./data.json:/app/data.json
